services:
#    cms.example:
#        class: Tucompu\CmsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
      webpage:
             class: Tucompu\CmsBundle\Infrastructure\Web\WebPage
             arguments:  ["@doctrine.orm.entity_manager","@service_container"]
                  # session: "@session"