<?php

namespace Tucompu\CmsBundle\Entity;

/**
 * ArticleTranslationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTranslationsRepository extends \Doctrine\ORM\EntityRepository
{
}
