<?php

namespace Tucompu\CmsBundle\Entity;

/**
 * BannerImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
