<?php

namespace Tucompu\CmsBundle\Entity;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends \Doctrine\ORM\EntityRepository
{
    public function ObtainBannerActiveImages()
    {
        $em = $this->getEntityManager();
        $banner = $em->createQuery(
            '
                SELECT bi,b FROM CmsBundle:BannerImages bi
                JOIN bi.banner b 
                WHERE b.isActive = true
            '
        );
        return $banner->getResult();
    }
}
