<?php

namespace Tucompu\CmsBundle\Entity;

/**
 * LanguagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagesRepository extends \Doctrine\ORM\EntityRepository
{
}
