<?php

namespace Tucompu\CmsBundle\Repository;

/**
 * SubMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
